### ISSUE TITLE
[Error] Very important

### ISSUE THREAD

**Issue by ensoulsharpassem** [Gecolay/GSit#100]
My server using "squaremap" web map plugins.

If use /bellyflop, and /lay command, not displayed on the web map.
But, use /sit command or Mouse Right Click to Sit on a stair, slab is displayed on the web map.

Very Very Irony haha

Fix please ♥
Thank you

**Comment by Gecolay** [comment]
This is not a GSit issue. The player is only invisible, not removed from the server. So I suspect that the squaremap plugin doesn't detect/show invisible players. They would have to implement a GSit check with the GSit-API to check if the player is posing and still display it on there map.

**Comment by ensoulsharpassem** [comment]
Can you delete this issue ?
