### ISSUE TITLE
/sit with SHOVEL bug

### ISSUE THREAD

**Issue by 0VERR** [Gecolay/GSit#104]
Hello, when right click on dirt with shovel or hoe while player is sitting he stand up, video: 
https://www.youtube.com/watch?v=EOapJ5_5Rlw

**Comment by 0VERR** [comment]
* even with protection region

**Comment by Gecolay** [comment]
> * even with protection region

this is an error by your region plugin

**Comment by Gecolay** [comment]
GSit only listens to the highest event priority. Therefore, this cannot be fixed by GSit
