### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by JuraRusan** [Gecolay/GSit#115]
Hello, I have already contacted #89, but then I didn’t pay attention to whether it helped or not, a couple of players noticed and notified that it still works.
https://youtu.be/RU6sFy_s_lM

Server version: `git-Paper-84 (MC: 1.20.1)`
Plugin version: `GSit-1.4.10`

It is possible to make a request for an improvement so that a player who flies on elytras could not transport another player in this way.?

Thank you in advance

**Comment by Gecolay** [comment]
Currently this is an intended feature of GSit.
Maybe I'll implement a new config option with a future update.

**Comment by Gecolay** [comment]
Since there are many other ways to fast travel with the PlayerSit feature, I would implement a general option for this to keep track of a few "fast travel" options. The Elytra option is too specific, so I won't implement it for now.
