### ISSUE TITLE
/Crawl does not ignore other plugins speed effects.

### ISSUE THREAD

**Issue by ShockCharge** [Gecolay/GSit#127]
Pretty much any plugin that gives speed, for example, custom enchantments like AdvancedEnchantments,
normal Minecraft potion effects, and skill plugins like AureliumSkills, McMMO, and EcoSkills.

Server:
![image](https://github.com/Gecolay/GSit/assets/48907444/963a7f7a-0659-485a-adee-238d7234ee42)
![image](https://github.com/Gecolay/GSit/assets/48907444/82ad424a-8979-4ae3-8160-a4969ebef737)

Conversation:
![image](https://github.com/Gecolay/GSit/assets/48907444/42a76275-a3a1-4eca-94ca-283f41b25627)

Video:
https://cdn.discordapp.com/attachments/743945414176276580/1177254944835903538/2023-11-24_03-30-09.mp4?ex=6571d71b&is=655f621b&hm=249df835e4abb80b81789685d1ad4b7f868157974fd84de1e6774eda0d8457c7&

**Comment by Gecolay** [comment]
With the current implementation of the crawl feature there is no workaround for this, because the server can't update this fast.
