### ISSUE TITLE
Glitch using sit on stair with a sign above it

### ISSUE THREAD

**Issue by o0sh4d0w0o** [Gecolay/GSit#128]
Hi,

Today we've got an issue with the plugin.

When a player is sitting (using right click) on stair with a sign placed above it (see screenshot below) the player pass through (and somthing across the floor in case of there is a whole behind) the block and is automaticly not flagged as sitted (that make sitting no more available for all other sittable blocs using right click) and if the player sitting another player and unsit he's teleported back to the last sitted block (the one that bugged)

We didn't test with other purposes but there is a possibility that this kind of bug is possible using other blocs liek traps etc..

The version used is the latest (we're on paper-1.20.2-318).

![image](https://github.com/Gecolay/GSit/assets/25451887/4750a7fa-192c-42f2-8699-19c4f790d117)

Hope you'll be able to reproduce it and fix it fast, thanks by advance.

**Comment by Gecolay** [comment]
I am currently unable to reproduce this on my test server. Can you post your plugin list or check if it works if you remove individual plugins?

**Comment by o0sh4d0w0o** [comment]
No plugin except gsit was used on the test server, blank paper vanilla server. This issue seems link to #133 as far the same behavior is produced (teleported to the last sitting position) and we got the underground noclip in addition when passing through the targetted block.

Sorry for the late answer.
