### ISSUE TITLE
Due to an error you can't pose here!

### ISSUE THREAD

**Issue by IAISI** [Gecolay/GSit#134]
When this event is cancelled via API:

https://github.com/Gecolay/GSit/blob/bbfdb9720f60d379c921ae111e4a6d10dc5c6fb6/core/src/main/java/dev/geco/gsit/manager/PoseManager.java#L79C28-L79C36

Player would see an error: Due to an error you can't pose here!

This is probably a mistake?

**Comment by Gecolay** [comment]
In the current implementation, there is no way to include another error message since all "failed" responses from the createPose method return null.

**Comment by IAISI** [comment]
Is there a way for another plugins to cancel poses without message?
