### ISSUE TITLE
Sitting on snow teleports player 1 block to the ground

### ISSUE THREAD

**Issue by bobhenl** [Gecolay/GSit#135]
Hi, there's bug! When you sit on the snow (just 1 layer), and then get up, it teleports you 1 block under it, so you're in the ground 1 block.
Like this:
![image](https://github.com/Gecolay/GSit/assets/18662086/7c8fffa6-63ec-4927-85ae-26f3f6ee8a4e)

**Comment by Gecolay** [comment]
I can't reproduce this. If this error still occurs with the latest GSit 1.7.0 version, please join the Discord server and post your server version and server type.

**Comment by IAISI** [comment]
It doesn't TP players into the ground anymore, but it would bug all plugins that store player location, for example commands like /back would be bugged if player would do:

/sit
/back (they TP away)
/back (they TP back to the location of /sit, and would get TPed 1 block too low here, allowing them to glitch thru 1 block walls downwards)
