### ISSUE TITLE
PrePlayerSitEvent renamed to PrePlayerPlayerSitEvent 

### ISSUE THREAD

**Issue by lucasfrederico** [Gecolay/GSit#136]
I noticed that in new versions the PrePlayerSitEvent event was renamed to PrePlayerPlayerSitEvent, is this correct? It looks like a typo.

**Comment by Gecolay** [comment]
"PrePlayerPlayerSitEvent" is for the PlayerSit feature. The "Player" prefix just shows, that this is a Player Event.
"PrePlayerSitEvent" was renamed to "PreEntitySitEvent.java".
