### ISSUE TITLE
Hangar build is outdated

### ISSUE THREAD

**Issue by DoodlesEpic** [Gecolay/GSit#138]
The plugin is available to download from GitHub, SpigotMC, and Paper Hangar. However, while the latest version available on GitHub and SpigotMC is 1.7.0, the version available on Hangar is still 1.5.3, which is not compatible with the latest Minecraft version.

It would be nice to have the latest build available on Paper Hangar too, or have it removed from there if there are no plans to upload the latest versions there.

**Comment by Gecolay** [comment]
Add 1.7.0 to Hanger
