### ISSUE TITLE
Can't Load In Folia

### ISSUE THREAD

**Issue by ddsb520** [Gecolay/GSit#141]
![image](https://github.com/Gecolay/GSit/assets/96320440/b97c5972-d387-43ed-a507-f0aa9e6f4b88)
Version: Folia 1.20.2

**Comment by Gecolay** [comment]
![image](https://github.com/Gecolay/GSit/assets/47757176/b89c9904-d191-4f96-893c-3e3c030d5daa)
1.20.2 Folia and 1.7.0 GSit works fine. Maybe check, if your Folia build is outdated

**Comment by ddsb520** [comment]
![image](https://github.com/Gecolay/GSit/assets/96320440/4a8119ec-9e33-4483-a9c2-3dc5c29c065c)
But Folia I just built yesterday

**Comment by ddsb520** [comment]
@Gecolay
