### ISSUE TITLE
[Bug] When sitting on a carpet and breaking it with water, you remain sitting in air

### ISSUE THREAD

**Issue by JorisvD01** [Gecolay/GSit#145]
Hey!
So basically the title. Whenever you place down a carpet, then sit on it and place water ontop the carpet will be broken by the water, but you remain in the sitting position. You can then break blocks around / below you and fly mid air while sitting.

I'm using the newest version of GSit (1.7.0) and Paper 1.20.1 (git-Paper-171)

![image](https://github.com/Gecolay/GSit/assets/99077822/695f3e52-eb05-46cd-9a20-bb9e63410270)

**Comment by Gecolay** [comment]
GSit doesn't check physical events in the world. The same thing happens with e.g. sand blocks.

**Comment by IAISI** [comment]
Would it make sense to add task to check players in pose say every 1 second and remove their pose if they lost ground?

**Comment by Grisous** [comment]
it only make server lags (if i remember well), Gecolay already answer that here or on his discord
