### ISSUE TITLE
右键地毯会从多人游戏断开连接（Right clicking on the carpet will disconnect from the multiplayer game）

### ISSUE THREAD

**Issue by Leoparking** [Gecolay/GSit#150]
<img width="1266" alt="image" src="https://github.com/Gecolay/GSit/assets/141799770/f7f2e5ac-2f0e-44cd-88eb-0d2a11f3f5a5">
服务器版本:mohist-1.20.1-550-server
客户端1.20.1

**Comment by Gecolay** [comment]
Looks like you reloaded the server. Try to restart it, there should be no problems,

**Comment by Leoparking** [comment]
> 看起来您重新加载了服务器。尝试重新启动它，应该没有问题，

WHAT？？
服务器不是一直开着吗
Isn't the server always on？？？
