### ISSUE TITLE
Bug with placeholderapi

### ISSUE THREAD

**Issue by NoltoxGit** [Gecolay/GSit#151]
Hello,
I've just noticed a new thing with placeholders, when I do a `/papi reload`, there are no more placeholders working and I have to restart my server to get them working again, it's not very practical :/

**Comment by Gecolay** [comment]
This does not sound like a issue from GSit. Please check what versions do you use and if another plugin changes placeholders.

**Comment by NoltoxGit** [comment]
Hello,
I've just tried it on a blank server with the latest version of Purpur, and the problem persists.
Logs : https://mclo.gs/kuNoyyb
