### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by vindognz** [Gecolay/GSit#155]
On my server running Paper 1.20.2, I was sitting in a boat with a player on my head, I then attempted to exit the boat, and the server instantly crashed. I believe I pressed SHIFT twice in quick succession, as I thought that it would remove the player, then dismount me from the boat.

**Comment by Gecolay** [comment]
Please upload the full server log

**Comment by vindognz** [comment]
Now I try and I fail to replicate it. That is so peculiar.

**Comment by Gecolay** [comment]
Please reopen the issue if you can replicate it.
