### ISSUE TITLE
<Gsit> When using PlayerSit, you can bypass the "worldguard<entry:DENY>"

### ISSUE THREAD

**Issue by BangXi** [gecolay/GSit#157]
Test Steps：
WorldGuard sets the __global__ <entry:DENY>
The player cannot move and cannot fly using fireworks
When using Gsit to ride on the player's head，The player below can move at will, and can fly by pressing and holding the firework all the time(elytra)
![Zulu-21 Screenshot 2024 05 08 - 00 34 14 28](https://github.com/Gecolay/GSit/assets/135555687/c2626ae9-3ef8-41be-b28b-eebe36f872ce)

git-Paper-496 (MC: 1.20.4)
plugins: (3)  worldguard-bukkit-7.0.9，worldedit-bukkit-7.3.0，GSit-1.9.1

**Comment by gecolay** [comment]
If I'm not mistaken, this should work with all mounted entities since WorldGuard can't really punish players for entering.

**Comment by BangXi** [comment]
> If I'm not mistaken, this should work with all mounted entities since WorldGuard can't really punish players for entering.

Thank you for your reply.
But I don't understand why the players below have players riding on their heads,The player below gets a movement exemption
Is this a problem with WorldGuard, I'm confused about it and don't know how to fix it
I'm currently temporarily disabling the "player sit" feature to fix it ...

**Comment by Kocimietka7192** [comment]
unfortunately I have the same problem
entry is deny
and if a player enters on the head, then normally two people legally go

**Comment by JosTheDude** [comment]
@gecolay As an alternative, could there be a way to unsit players when they enter a sit deny region in worldguard? :)
