### ISSUE TITLE
GSit crash upon dismounting a mount while a player rides you

### ISSUE THREAD

**Issue by kaweepatinn1** [gecolay/GSit#159]
This is 100% a GSit crash. Tested again where the player is ridden by another player and dismounts a mount, crash works so far with both horse and boat.

Latest version, 1.20.4.

Crash logs at:
https://github.com/gecolay/GSit/issues/158

I welcome you to deny that it is a GSit crash, but I have tested it and GSit is the only issue. No crashes except when the player is riding another player through GSit and dismounts a mount. Perhaps due to the crouch trying to call both dismounting the player on top and the mount at the same time.

**Comment by kaweepatinn1** [comment]
Tested again, seems to happen inconsistently at times, we just tested it with no crash thrice with a horse, and on first attempt at boat dismount the server crashed.

**Comment by kaweepatinn1** [comment]
Downgrading to 1.8.0 still causes the issue.

**Comment by gecolay** [comment]
I can't reproduce this error. The crash message only lists Minecraft Vanilla Server components causing this problem, so it's almost impossible to figure out where exactly the error is coming from.
I'm sorry if this is the reason GSit isn't working on the server, and I'd really like to get it working, but I don't have a starting point to look from here.
