### ISSUE TITLE
Unable to dismount if sitting on the head of someone sitting.

### ISSUE THREAD

**Issue by mibby** [Gecolay/GSit#16]
Compiled as of commit https://github.com/Gecolay/GSit/commit/defd42654885fc6f30f22e4d7a808000c62930b5

If you sit on someone's head while they are already sitting on the ground, the person sitting on the head cannot dismount unless the vehicle (bottom player) stands up and hits shift.

* Sit down on a slab or floor.
* Have someone come up to you and sit on your head with right click.
* They are now stuck and cannot dismount with Shift.

**Comment by Gecolay** [comment]
Can you please share information about your server environment?
