### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by foxya27** [gecolay/GSit#161]
![image](https://github.com/gecolay/GSit/assets/95995512/12435d7c-3ba8-4e72-b496-f6eafe27f594)
When downloading from Spigot or Github, Windows Antivirus detects a virus

**Comment by foxya27** [comment]
My system is in Russian, but I think it won’t be difficult for you to translate the error code “Virus detected”

**Comment by gecolay** [comment]
Some Browsers detect ".jar" files as potentially dangerous.
