### ISSUE TITLE
When a player has another player on his head, he can't be teleported into another world

### ISSUE THREAD

**Issue by homerek111** [gecolay/GSit#170]
I'm sitting on my alt account, and am running command like:
/execute in minecraft:the_nether run tp NICK 100 100 100
however, he can't be teleported. if I get off his head, and rerun the cmd, it works fine

+ the same command works fine with player on head WHEN they are already standing in this world - so this bug happens only when you try to teleport into another world

**Comment by gecolay** [comment]
Fix #170

**Comment by gecolay** [comment]
This is fixed by allowing the command blacklist to blacklist commands for PlayerSit players, as I cannot fix this issue as this is the way Minecraft handles vehicles.

**Comment by homerek111** [comment]
> This is fixed by allowing the command blacklist to blacklist commands for PlayerSit players, as I cannot fix this issue as this is the way Minecraft handles vehicles.

@gecolay but is that something that you will implement in next update or it's a feature that should be avaiable in current version...? I think current CommandBlacklist works only for sitting on the ground - not for PlayerSit. 

The problem described in this bug report is happening FOR PLAYERS THAT HAVE ANOTHER PLAYER ON THEIR HEAD. So GSit plugin should block executing blacklisted commands not only for sitting players but also for those who have someone on their head

**Comment by gecolay** [comment]
TH next update 1.9.6 (which you can already download here on GitHub) fixes the command blacklist to work for the full PlayerSit feature
