### ISSUE TITLE
Ghost player while using under slabs

### ISSUE THREAD

**Issue by MeowIce** [gecolay/GSit#172]
https://github.com/user-attachments/assets/d02fa396-b589-4d4a-ae61-456e3a8a57cd

https://github.com/user-attachments/assets/d23cc378-7d28-405a-a26f-213c2d2cc7e4

### Steps to reproduce:

https://github.com/user-attachments/assets/1e294c09-c899-4cab-b009-63e4e356f9a8

**Comment by gecolay** [comment]
Even using your "Steps to reproduce" video, I am unable to reproduce this on a simple server with the latest GSit version.
