### ISSUE TITLE
[Feature Request] Double-click to sit

### ISSUE THREAD

**Issue by DaniDipp** [gecolay/GSit#173]
Hello!
Would it be possible to add a feature that activates the sit function only after clicking twice in a second? I understand that there is the `/sit toggle` command to prevent accidental activations, but it's pretty clumsy to use. Requiring a double-click would be a lot more intuitive and immersive.
Thanks in advance!

**Comment by gecolay** [comment]
To prevent accidental activations of the sit feature you can enable the `empty-hand-only` config option to only sit with an empty hand.
