### ISSUE TITLE
Crawling at a weird height shows the shulker head.

### ISSUE THREAD

**Issue by Goinging** [gecolay/GSit#175]
![image](https://github.com/user-attachments/assets/f0b582c8-f991-47b4-bf1c-fc9a75b29d28)

**Comment by gecolay** [comment]
works as intended. can't be recoded with the current minecraft versions.

**Comment by VincentX0905** [comment]
It will also be displayed on incomplete blocks.
like slab, stairs, dirt path, mud, soul sand etc.

**Comment by gecolay** [comment]
Yes this is correct.
