### ISSUE TITLE
incompatibility of the generic.scale attribute in 1.21.x with the /crawl command

### ISSUE THREAD

**Issue by conscnt1** [gecolay/GSit#180]
https://github.com/user-attachments/assets/93415ad4-acbc-4a9b-bdcf-8e978fce21b3

this happens when I use size 0.55 (exactly one block), I think it won't be easy to fix, but I'll write this ticket anyway

**Comment by gecolay** [comment]
The problem here will most likely be the high speed value. The crawl function cannot handle high speed values ​​properly. I will try to fix the animation behavior for small scales with version 1.21.3

**Comment by gecolay** [comment]
The scale attribute can currently only be implemented for the "pose" features. Maybe this will be possible in a future update, but currently there are too many problems with it.
