### ISSUE TITLE
Crash Caused by Interaction Between GSit and EssentialsX Vanish

### ISSUE THREAD

**Issue by DarkChromaMC** [gecolay/GSit#184]
We’ve identified a crash that occurs when a staff member using the /vanish command (via EssentialsX Vanish) moves while another player is sitting on them using the GSit plugin's player sit feature. The issue appears to be related to how the server handles movement tracking while a player is vanished.

#### **Steps to Reproduce**  
1. A staff member enables `/vanish` using EssentialsX Vanish.  
2. A non-vanished player uses the GSit plugin's player sit feature to sit on the vanished player.  
3. The vanished staff member moves and their movement is not recorded by the server in real-time.

#### **Observed Behavior**  
- The server crashes after some time because of chunk loading issues
- Movement of vanished players is not recorded properly (unless its the vanilla vanish effect), leading to chunk issues.  

#### **Additional Notes**  
- This only happens when using `/vanish` because movements are not showing in real-time by the server until vanish is turned off. However, when using vanish effects from potions, movements are recorded as expected.  

#### **Potential Causes?**  
- GSit’s player sit feature interacting improperly with EssentialsX Vanish.  
- Movement tracking discrepancies for vanished players in EssentialsX.  

https://youtu.be/TdIqGeCfKQM
https://youtu.be/VYQqOqSBlWI

**Comment by gecolay** [comment]
The Vanish plugin should dismount all player passengers before the player gets invisible. The Vanish plugin should add a fix for this.
