### ISSUE TITLE
Shift + Right Click to PlayerSitPlayer

### ISSUE THREAD

**Issue by Stokmenn** [gecolay/GSit#188]
Can you add to config either right click to sit, or SHIFT + right click?

Many servers have Right Click on other functions, and would be cool if you have a choice to configure how to sit to player.

**Comment by gecolay** [comment]
> Can you add to config either right click to sit, or SHIFT + right click?

We can't use shift to sit down. Otherwise the player would directly get up.

**Comment by OakLoaf** [comment]
I like this idea, the player doesn't necessarily have to get directly back up, you could add a short cooldown period after they sit before they are able to stand back up
