### ISSUE TITLE
website share question

### ISSUE THREAD

**Issue by hpwriterkyle** [gecolay/GSit#189]
may i move the plugin into a new chinese minecraft website?
chinese demand the resource in a new formus since the originally largest chinese minecraft formus fell down.
could u permit me to?

**Comment by gecolay** [comment]
This is possible if you always link to this GitHub repository (https://github.com/gecolay/GSit) and the official Spigot page (https://www.spigotmc.org/resources/gsit.62325/) and credit me as the official author and owner of the code and plugin.
