### ISSUE TITLE
Items are duplicated in some anims

### ISSUE THREAD

**Issue by quillincn** [Gecolay/GSit#20]
In /lay, /bellyflop and /spin, item`s in hand are are duplicated. It cose the real player located near NPC, which has been placed on his spot, i think.

I using the last version of GSit and Paper 1.18. Some screenshots:
https://imgur.com/a/yWen8NC

**Comment by Gecolay** [comment]
This only happens when you are in creative mode. For every other mode this works as intended.

**Comment by quillincn** [comment]
Thank you very much!
