### ISSUE TITLE
Overrides Essential Homes when use-home is disabled

### ISSUE THREAD

**Issue by BossEliminated** [Gecolay/GSit#26]
When use-home is false. Very stupidly, the home command is just disabled. So you can't use the essential home features. It's better for a few reasons, you can configure the teleport delay which is a waiting time before you can teleport to prevent players from disappearing if they are losing a fight. So no teleport delay. And there is no /sethome, /delhome command variant. There is no /homes command you have to type /home homes which is stupid. So, please fix the bug compatibility issue. use-home = false should only disable the Gwarp home feature, as you can disable essentials home from essentials. For now, I'm using your home system with MyCommands to do the stuff that you haven't got. All, so I can use the warp feature, not ideal.

**Comment by Gecolay** [comment]
wrong plugin
