### ISSUE TITLE
Gsit Featured on Category5 Technology TV

### ISSUE THREAD

**Issue by Cat5TV** [Gecolay/GSit#28]
Hi @Gecolay -
Not an issue, but since you don't have contact info on GitHub, I thought I'd reach out this way.

Congrats: We featured Gsit on a recent episode of Category5 Technology TV :)

https://www.youtube.com/watch?v=4YgS5M4t_Qg

Keep up the great work! Adding Gsit to our official Patron server as well.

**Comment by Gecolay** [comment]
Thank you so much! Great video!
