### ISSUE TITLE
Player facing the wrong direction when sitting on stairs

### ISSUE THREAD

**Issue by BetTD** [Gecolay/GSit#40]
# Bug Description

As of the latest update, it seems like sitting on a stairs block no longer positions the player's body facing the same direction as the stairs. Instead, the player is positioned always facing south, regardless of the orientation of the stairs. This wasn't the case prior to this update, as can be seen here:

## v1.0.9:

![image](https://user-images.githubusercontent.com/10455943/170813191-235cfa69-15a8-402d-82b9-4e20bd53239b.png)

![image](https://user-images.githubusercontent.com/10455943/170813290-f989940d-7228-4c0b-a7d2-5320e542815f.png)

## v1.0.8:

![image](https://user-images.githubusercontent.com/10455943/170813276-fe392552-af0b-4efd-bed2-6bb897bd822a.png)

![image](https://user-images.githubusercontent.com/10455943/170813225-0fb6a289-3e0d-4330-9100-1134733ac46b.png)

As you may be able to tell, in the latest plugin's release my player's body is always being forced to be facing south, while in the previous release my body was always forced to be facing the same way as the stairs.

I believe this to be a bug, as it was not documented in the changelog and the old behavior just feels right.

# Environment

Testing was done on two different servers. Both are running a custom fork of Pufferfish for Minecraft 1.17.1:

```
This server is running Tortilla version git-Tortilla-"2feb4fd" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2feb4fd)
Unknown version
Previous version: git-Tortilla-"1e3712a" (MC: 1.17.1)
```

The only difference between both servers is the version of GSit that they're running.

**Comment by Gecolay** [comment]
Thank you for this report! I'll check this as soon as possible!
