### ISSUE TITLE
Vanish issue

### ISSUE THREAD

**Issue by Lorias-Aegorin** [Gecolay/GSit#41]
Good day,

It was discovered that when players lie down in Vanish, they become visible to all players.

1.18.2-Paper-341
GSit 1.0.10

![grafik](https://user-images.githubusercontent.com/62625225/171681658-a3a2aef9-5044-451f-915d-9bd0998f27d5.png)
![grafik](https://user-images.githubusercontent.com/62625225/171681679-e6e65d18-ab25-4cdb-aad3-ba6e4b825632.png)

**Comment by Gecolay** [comment]
I'll try to create a workaround!
