### ISSUE TITLE
Sliding into Ground Bug - Slide to activate Crawl

### ISSUE THREAD

**Issue by JaHollTV** [Gecolay/GSit#42]
![image](https://user-images.githubusercontent.com/48917504/173041085-8c95f793-747b-4af9-898c-fad4fa1a22f6.png)
As you can see in the image the slide often bugs into the Ground. 

For our realistic roleplay Server it would be awesome, if it would work better.
Alternative you could add an config option, that when the slide is triggered the player will just to start crawl 
(maybee with a little speed increasement or something).

**Comment by Gecolay** [comment]
what do you mean by "the slide"?

**Comment by Gecolay** [comment]
pls provide more info

**Comment by Gecolay** [comment]
This is not a GSit feature...

**Comment by JaHollTV** [comment]
oh my god, i feel so stupid in this moment xD
Sorry!

#close
