### ISSUE TITLE
PlayerSit update

### ISSUE THREAD

**Issue by moderator10000078** [Gecolay/GSit#45]
it seems to me it is worth adding 2 functions, this is switching whether other players can sit on the player, and determining the distance from which you can sit (well, or impose the same as in / sit)

**Comment by Gecolay** [comment]
there is a "/sit playertoggle" command for the first thing.
I will consider implementing the second feature.

**Comment by Gecolay** [comment]
implemented!

**Comment by moderator10000078** [comment]
as far as I understand /sit playertoggle switches the ability to sit on other players, I would like another command that would allow/forbid other players to sit on me

**Comment by Gecolay** [comment]
@moderator10000078 that's the same command. you allow/forbid others to sit on you and you can/can't sit on others
