### ISSUE TITLE
Dolphins grace lets you fly 

### ISSUE THREAD

**Issue by DerpDerpling** [Gecolay/GSit#52]
So, if you have dolphins grace and crawl, you start flying. my server has different regions that give effects, and one of them is dolphins grace. so i had players flying all over the place. heres a video of it in action.

https://user-images.githubusercontent.com/57187871/177439857-72aba529-f5bb-4dc1-abdc-b3924f71e64b.mp4

**Comment by Gecolay** [comment]
I can't reproduce this on my test server. can you provide more info about your server environment?

**Comment by DerpDerpling** [comment]
Oh I'm sorry I swear I replied to this,

I was on purpur 1.19 I think build 1700 at the time? Its still happening
