### ISSUE TITLE
Cant cancel events

### ISSUE THREAD

**Issue by Lorias-Aegorin** [Gecolay/GSit#58]
A small question. 

Why don't you allow the event to be canceled when players want to stand up via shift or with /sit? The function would have saved me a lot of code and work, so it is a tinkering around for me that I have to code significantly more lines in certain use-cases.

![grafik](https://user-images.githubusercontent.com/62625225/183145511-c11a7f40-3ed8-44f6-971a-688afe3e7e7c.png)
![grafik](https://user-images.githubusercontent.com/62625225/183145566-e78012ad-e09d-4a5b-ad68-1385f89eafd4.png)

**Comment by Gecolay** [comment]
If you cancel the [EntityGetUpSitEvent](https://github.com/Gecolay/GSit/blob/main/core/src/main/java/dev/geco/gsit/api/event/EntityGetUpSitEvent.java) players should not be able to get up by sneaking or /sit
