### ISSUE TITLE
Swift Sneak III enchantment breaks crawling

### ISSUE THREAD

**Issue by holli2801** [Gecolay/GSit#61]
I noticed that when you have the Swift Sneak III enchantment on your leggings and you do /crawl you bump up and down when you move. 
Basically the placement of the barrier block above the player is too slow for the faster crawling speed. (didnt test with speed effect but probably makes it worse)
This interrupts the crawling movement because the player stands up and gets back down on every block it travels

**Comment by Gecolay** [comment]
I'll check this.

**Comment by Gecolay** [comment]
I can reproduce this, but there isn't really anything that can be done about it at this time. Maybe in the future with a different system.
