### ISSUE TITLE
Event needed to detect when somebody is sitting down

### ISSUE THREAD

**Issue by mrgeneralq** [Gecolay/GSit#62]
Hello again

So I just checked and the API has a feature to detect if somebody is sitting down.
However I was wondering if there is an event that represents if somebody sat down so I could implement a listener?

Specifically I'm looking to detect when people are sleeping with /lay.
Currently making a hook with sleep-most towards GSit

**Comment by Gecolay** [comment]
Check the [PlayerPoseEvent](https://github.com/Gecolay/GSit/blob/main/core/src/main/java/dev/geco/gsit/api/event/PlayerPoseEvent.java). There you can get "getPoseSeat()" from there you can make "getPose()". Check if this pose is "SLEEPING".
