### ISSUE TITLE
Problem with Permissions

### ISSUE THREAD

**Issue by rockit7** [Gecolay/GSit#64]
Is there any chance the plugin doesn't respect the permissions? I don't want everyone having the "default permission", so they are set to false in luckperms. The higher ranks, however cannot use the commands as they are negated for the lower ranks. I went back to the previous version of 1.1.2, and it seems to work again. This worked perfectly before updating to 1.19.2.

**Comment by Gecolay** [comment]
Please check the latest version and reopen an issue if you're still having permissions issues.
