### ISSUE TITLE
Alternative methode - MManager#toFormattedComponent()

### ISSUE THREAD

**Issue by BlockyTheDev** [Gecolay/GSit#67]
https://github.com/Gecolay/GSit/blob/284f49cf3ce33d2ed5dea51df7a3732930b11367/core/src/main/java/dev/geco/gsit/manager/MManager.java#L129-L135

In the last minutes I wrote code for a private Spigot-Plugin with the same function, which is working with a StringBuilder and a start-position variable, which hasn't any restrictions, like in the mentioned code, where Hex-Colors aren't translated when there is a `:`-symbol in front of the pattern and so doesn't need any if statement in the while loop.

Is there any interest to replace the inbuilt methode? If yes, just write, so I can create a pull request.

~ I like people, who are making their projects OpenSource for such possibilities.

**Comment by Gecolay** [comment]
You can open a pull request, I'll check it

**Comment by Gecolay** [comment]
I check for the :-symbol so a string like "<color:#123456>Test</color>" does not replace the hex-color with another "<reset><color:#123456>"

**Comment by BlockyTheDev** [comment]
> I check for the :-symbol so a string like "color:#123456Test" does not replace the hex-color with another "color:#123456"

Yes, I found it out after a bit of testing 😂 



> You can open a pull request, I'll check it

I will open one in this night, or when I don't find the time before sleeping anymore, I will open one after. I just asked because I already made a pull request to an other project on github and then a contributor of that project closed it and said that they are not interested in pull requests...
