### ISSUE TITLE
People sitting on people

### ISSUE THREAD

**Issue by mrcoffee1026** [Gecolay/GSit#71]
They get the message "Someone is sitting here already." But clicking on a slab outside the hitbox of the arrow allows a second person to sit "inside" the first person (does not work for a third).

GSit 1.2.7
paper 183

**Comment by Gecolay** [comment]
can you provide a video to show this?

**Comment by Gecolay** [comment]
Thank you! I'll check what causes this error and will fix it!

**Comment by Gecolay** [comment]
Should be fixed with the latest version 1.2.9
