### ISSUE TITLE
SkinsRestorer incompatibility

### ISSUE THREAD

**Issue by xknat** [Gecolay/GSit#73]
Hey there!
We from [SkinsRestorer/SkinsRestorerX](https://github.com/SkinsRestorer/SkinsRestorerX) received a bug report from @MarissaKirisame about a skin refresh client desync where the player was using gsit to "ghost walk". We were not able to resolve the issue, maybe you can have a look at it?
Our ticket: https://github.com/SkinsRestorer/SkinsRestorerX/issues/1016
information: 
**GSit is v1.2.5**
**SkinsRestorer 14.2.4**

Server: 
`Airplane version git-Airplane-"74774a0" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 74774a0 on ver/1.17)`

Plugins (44): 
`AuthMe, BungeeChatBridge, Citizens, CrackShot, CustomBiomeColors, Denizen, DiscordSRV, Duels, dynmap, Essentials, EssentialsChat, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), GadgetsMenu, GrapplingHook, GSit, HolographicDisplays, IllegalStack, ImageOnMap, LiteBans, LuckPerms, Matrix, Multiverse-Core, Multiverse-Inventories, NightRealm, NoChatLagServer, PlaceholderAPI, PlayerVaults, PlotSquared, PluginFramework, ProtocolLib, Sentinel, Shopkeepers, SkinsRestorer, StayPut*, SuperbVote*, TAB, Vault, Vehicles, ViaVersion, VoidGenerator, Votifier, WorldGuard, WorldGuardEvents`

Bungeecord: 
`Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504 by md_5`

Plugins: `SkinsRestorer`

**Comment by xknat** [comment]
@Gecolay any update on this?

**Comment by Nimaari** [comment]
That's alright, take your time. Wish you good luck on your other projects. I was the one who made the report, also, since @xknat didn't send it above (or maybe I'm just blind), here's video evidence of the bug. 
https://streamable.com/eud8ah

**Comment by StKillReal** [comment]
Fullly agree, players just use /skin <name> (even with this command blocked in config.eml) during sit/lay and can just walk like a ghost. Their body just sit/lay while they walking around

**Comment by xknat** [comment]
> even with this command blocked in config.eml
command is run trough proxy, so can not be blocked by backend

**Comment by Gecolay** [comment]
There's currently no nice way to detect these changes when they're being performed by the proxy. If the plugin is running on the server itself, the configuration blocks the command and everything works as intended.
As such, this cannot currently be fixed unless someone else has a good idea.

**Comment by xknat** [comment]
> There's currently no nice way to detect these changes when they're being performed by the proxy. If the plugin is running on the server itself, the configuration blocks the command and everything works as intended. As such, this cannot currently be fixed unless someone else has a good idea.

Refreshing the skin is done on the backend to send a packet to refresh the player skin.
If there is a API, we could unsit the player, refresh the skin, put the player back in sitting.
Please let me know which API we would need to use to do this

**Comment by Gecolay** [comment]
@xknat the problem is that the plugin is running on the proxy in this scenario here. You cannot access the events from GSit as it runs directly on the server. If you use the server version of SkinsRestorerX, the command is correctly blocked by the config file.

**Comment by Gecolay** [comment]
API: [Link](https://github.com/Gecolay/GSit/blob/main/core/src/main/java/dev/geco/gsit/api/GSitAPI.java)

There is a removeSeat api-function you can use if you access GSit on the server
