### ISSUE TITLE
GSit too high

### ISSUE THREAD

**Issue by lynrayy** [Gecolay/GSit#79]
![image](https://user-images.githubusercontent.com/59417884/205162419-bb83ad23-249d-462d-92f3-16517e60a727.png)
It is too high, how to make it lower?

**Comment by Gecolay** [comment]
Not possible because of the player hitbox.

**Comment by Gecolay** [comment]
otherwise the hitbox would stuck in the other player

**Comment by lynrayy** [comment]
I want it lower and dont mind about hitboxes
There are a lot of emotions in emotecraft that made for lower sit
