### ISSUE TITLE
/lay duplicates player names in tab list each time the player uses /lay

### ISSUE THREAD

**Issue by Moranyixiao** [Gecolay/GSit#82]
/lay duplicates player names in tab list each time the player uses /lay
![}X~Q(D2~HPEIZKT TX2UMID](https://user-images.githubusercontent.com/26624650/210048441-f214ff00-ec30-4aca-9fc9-140659495da7.png)
the lay and bellyflop command also shows 2 characters on top of each other

**Comment by Folas1337** [comment]
Can confirm, same is happening to me using the TAB plugin.

**Comment by ArmonicPvP** [comment]
Can confirm this also happens for me.

**Comment by Gecolay** [comment]
Should be fixed with the latest release.
