### ISSUE TITLE
Can't use riptide trident with player on head

### ISSUE THREAD

**Issue by Owehttamy** [Gecolay/GSit#84]
If a player sits on your head, you can't use a riptide trident.
Instead, it will damage the player above you and cancel the trident's movement.

This could be considered intentional, but with how you cannot punch your passengers or shoot projectiles at them, I think this is also worth changing.

**Comment by Gecolay** [comment]
I can reproduce this, but currently this cannot be fixed. The trident looks for the hitbox in a different way that I can't currently check against.

**Comment by Owehttamy** [comment]
Why not move the players above you slightly out of the way when charging a trident or something?

**Comment by Gecolay** [comment]
where should they be moved??

**Comment by Owehttamy** [comment]
Why not simply up a block or two, just out of the radius of the hitbox detection, until the riptide action is over?
