### ISSUE TITLE
Players can sit on other players in unsafe locations

### ISSUE THREAD

**Issue by Owehttamy** [Gecolay/GSit#85]
If a player attempts to sit on their friend when they could suffocate from the blocks above them, the plugin will still let them get on top of the player and take damage.
How about implementing a check if there is an opaque block above a player when allow-unsafe is false?

**Comment by Gecolay** [comment]
This would not help at all, because a player can just move out of a house stack up to 5 players and walk in. they will get damage again. so the check outside whould call: yes everything is fine, no block above the player
