### ISSUE TITLE
Player cannot teleport if being sat on

### ISSUE THREAD

**Issue by Boothin** [Gecolay/GSit#87]
With the latest couple versions, if a player is being sat on, they can no longer be teleported. Using the default minecraft teleport command does not move the player, nor does using something like essentials teleports. There is no error, it says the player is teleported but they don't move.

**Comment by Gecolay** [comment]
Using the default teleport command with the latest GSit version 1.3.3 I can't reproduce this.

**Comment by Gecolay** [comment]
I added an extra check that dismounts players when a player below teleports.
