### ISSUE TITLE
Publish GSit API to a maven repository

### ISSUE THREAD

**Issue by raikasdev** [Gecolay/GSit#9]
Most plugins nowdays use Maven as their dependency manager (like you do), and it would be more useful for you to provide your API on Maven so it can be more easily used.

**Comment by Lorias-Aegorin** [comment]
It would be quite handy to do the whole thing, because we would like to hook into GSit for a plugin from our side ^^''

**Comment by mrgeneralq** [comment]
+1, I just had someone requesting to hook SleepMost with this plugin, but then it would need maven support.

**Comment by Boy0000** [comment]
https://repo.mineinabyss.com/#/releases/com/gecolay/gsit

Our project has gone ahead and put it on our maven repo for the time being.
Until theres an actual one you could use it @mrgeneralq  @Lorias-Aegorin

**Comment by mrgeneralq** [comment]
Fantastic!

**Comment by Gecolay** [comment]
I'm working on a release with https://jitpack.io

**Comment by Lorias-Aegorin** [comment]
> https://repo.mineinabyss.com/#/releases/com/gecolay/gsit
> 
> Our project has gone ahead and put it on our maven repo for the time being. Until theres an actual one you could use it @mrgeneralq @Lorias-Aegorin

And how do I use it? I tried to use the last available api for maven but when I paste it and reload maven I don't get any libary to work with ^^''

**Comment by Gecolay** [comment]
Maven repository will be available with the next update 1.3.1
https://www.spigotmc.org/resources/GSit.62325/field?field=documentation
