### ISSUE TITLE
/lay with invisibility will remove the invisibility when coming out of it

### ISSUE THREAD

**Issue by JamieOnSootMC** [Gecolay/GSit#91]
Version: GSit-1.1.2
Server: Purpur 1.19

Basically when you do /lay and you have the invisibility potion effect, the effect will get toggled off by the plugin, showing the player on the ground while the potion effect itself will still remain, then when standing up using the crouch key, the player will still be visible despite the player having an invisibility effect.

I'd assume it'd be an easy fix, just run a check to see if the player has the invisibility potion effect and if they do don't alter the visibility.

**Comment by JamieOnSootMC** [comment]
Also don't question why im using such an old version, its the one my manager put on there and I dont have access to change it lol

**Comment by bobhenl** [comment]
Looks like to be issue again @gecolay
