### ISSUE TITLE
Pose error if event cancelled

### ISSUE THREAD

**Issue by Lorias-Jak** [Gecolay/GSit#92]
I am currently programming with the GSit API and am working on the "PrePlayerPoseEvent" and canceling it in certain cases. When I cancel it, a message comes in the chat that I can't turn off. Do you have any idea how I can get rid of it? Or is this a bug that is unintentional?
I use Paper-388 and GSit 1.3.6

Here is an excerpt of the message that comes in the chat
![grafik](https://user-images.githubusercontent.com/62625225/217377998-de4b7481-35c7-4b1b-9599-37767be58135.png)

**Comment by Gecolay** [comment]
If you any pose command ("/lay", "bellyflop", ...) and the command fails, (because of an event beeing canceled or any internal error, this message appears)
